/**
 * Knowledge Gap Detection — Type Definitions
 *
 * A "knowledge gap" represents a structural or semantic weakness
 * in the user's knowledge graph that could be improved by adding
 * links or creating new bridging notes.
 */

// ── Gap Types ──────────────────────────────────────────────────────────

/** The category of knowledge gap detected. */
export type GapType = 'cluster_gap' | 'orphan_gap' | 'concept_gap';

/** The kind of remediation suggested for a gap. */
export type GapActionType = 'link' | 'create_note';

// ── Suggested Action ───────────────────────────────────────────────────

/** A concrete suggestion for how to resolve a knowledge gap. */
export interface GapSuggestedAction {
  /** Whether to link existing notes or create a new bridging note. */
  type: GapActionType;
  /** Human-readable description of the suggested action. */
  details: string;
}

// ── Knowledge Gap ──────────────────────────────────────────────────────

/**
 * Represents a single detected knowledge gap.
 *
 * Each gap includes a confidence score (0–1) and a suggested
 * remediation action. Gaps are generated by the detector and
 * consumed by the UI dashboard.
 */
export interface KnowledgeGap {
  /** Unique identifier for this gap instance. */
  id: string;
  /** The category of gap detected. */
  type: GapType;
  /** Human-readable explanation of the gap. */
  description: string;
  /** Note IDs that participate in or define this gap. */
  involvedNotes: string[];
  /** Confidence score from 0 (uncertain) to 1 (highly confident). */
  confidence: number;
  /** Suggested action to resolve the gap. */
  suggestedAction: GapSuggestedAction;
}
