import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const vaultPluginDir = "C:/Users/rajve/OneDrive/Documents/Obsidian Vault/.obsidian/plugins/obsidian-graph-intelligence";

const copyToVaultPlugin = {
  name: "copy-to-vault",
  setup(build) {
    build.onEnd(() => {
      try {
        if (!fs.existsSync(vaultPluginDir)) {
          fs.mkdirSync(vaultPluginDir, { recursive: true });
        }
        ["main.js", "styles.css", "manifest.json"].forEach((file) => {
          if (fs.existsSync(file)) {
            fs.copyFileSync(file, path.join(vaultPluginDir, file));
          }
        });
        console.log(`[${new Date().toLocaleTimeString()}] ✅ Build copied to Obsidian vault!`);
      } catch (err) {
        console.error("❌ Failed to copy to vault:", err);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [copyToVaultPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
