import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Opt-in auto-deploy. Builds copy main.js/styles.css/manifest.json into a vault
// plugin folder ONLY when OBSIDIAN_VAULT_PLUGINS_PATH is set (point it at the
// plugin's own folder, e.g. ".../.obsidian/plugins/obsidian-graph-intelligence").
// This used to be a hardcoded path, which meant every git worktree's build wrote
// to the SAME vault folder and clobbered each other when multiple builds ran in
// parallel. Gating on an env var keeps a stray `npm run build` from touching any
// vault unless you explicitly asked for it. For one-shot deploys use `npm run deploy`.
const vaultPluginDir = process.env.OBSIDIAN_VAULT_PLUGINS_PATH || "";

const copyToVaultPlugin = {
  name: "copy-to-vault",
  setup(build) {
    build.onEnd(() => {
      if (!vaultPluginDir) return;
      try {
        if (!fs.existsSync(vaultPluginDir)) {
          fs.mkdirSync(vaultPluginDir, { recursive: true });
        }
        ["main.js", "styles.css", "manifest.json"].forEach((file) => {
          if (fs.existsSync(file)) {
            fs.copyFileSync(file, path.join(vaultPluginDir, file));
          }
        });
        console.log(`[${new Date().toLocaleTimeString()}] Build copied to Obsidian vault.`);
      } catch (err) {
        console.error("Failed to copy to vault:", err);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [copyToVaultPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
